---
title: "Introduction to Visualisation with RStudio"
subtitle: "Massey University"
date: "28th June 2021"
output:
  html_document:
    mathjax: null
    highlight: null
    self_contained: false
    theme: null
    css: default.css
---

Introduction to Visualisation with RStudio is a 2 hour zoom session introducing
people to how to produce charts of data using `ggplot2` in RStudio.

The presenter is Jonathan Marshall.

### What will it be like?

We'll use zoom for presentation and live demonstration and utilise breakout rooms to give you the chance to practice what you've learned. Each breakout room will have an experienced RStudio user to help you out.

### Who should attend?

This workshop is aimed at people who are just starting out with R and RStudio or `ggplot2`. We assume
that we might have some attendees opening R and RStudio for the first time, or perhaps using `ggplot2`
for the first time.

If you're already familiar with R and RStudio, specifically with the `ggplot2` package for creating
charts, then consider attending as a helper for the breakout rooms - helping others is an excellent
way to help reinforce your own knowledge!

### Preparation

You'll need a device that can both run RStudio as well as Zoom. We recommend a laptop or desktop computer so that you can share your screen.

If you haven't already, please install R and RStudio before the workshop:

[Click here for instructions on downloading and installing R and RStudio](downloading.html)

We recommend R version 4.0 or higher, and RStudio v1.4.

In addition, download the materials below:

### Materials

Presentation slides are linked below.

All the material for exercises are available [in this zip file](intro_to_vis.zip). Unzip this to a convenient location, and open up `intro_to_R.Rproj` to load RStudio.

### Content

We'll be covering:

- The use of `ggplot2` for charts in RStudio.

- The **Recipe** of a `ggplot2` chart.

- How to map your data to features of a chart.

- How to change aesthetics.

- Using more than one geometric layer in a chart.

- Labeling charts.

- Changing scales and adding colour.

[Click here for the slides.](visualisation.html)

### Solutions

Solutions to the exercises will be available [in this zip file](visualisation_solutions.zip) after the session.

### Source code for material

[The course Github repository](https://github.com/jmarshallnz/intro_to_r/tree/visualisation_by_zoom) has all the R markdown files that produced the slides in case you're interested :)
